#!/usr/bin/env python3

import sys
a = int(sys.argv[1])
b = a - 3500
if b <= 0:
    print(format(0, '.2f'))
elif b > 0 and b <= 1500:
    c = b * 0.03
    print(format(c, '.2f'))
elif b > 1500 and b <= 4500:
    c = b * 0.1 - 105
    print(format(c, '.2f'))
elif b > 4500 and b <= 9000:
    c = b * 0.2 -555
    print(format(c, '.2f'))
elif b > 9000 and b <= 35000:
    c = b * 0.25 - 1005
    print(format(c, '.2f'))
elif b > 35000 and b <= 55000:
    c = b * 0.3 - 2755
    print(format(c, '.2f'))
elif b > 55000 and b <= 80000:
    c = b * 0.35 - 5505
    print(format(c, '.2f'))
else:
    c = b * 0.45 - 13505
    print(format(c, '.2f')
